### ISSUE TITLE
The phone number label is hidden.

### ISSUE THREAD

**Issue by franco27** [FossifyOrg/Phone#129] opened 2024-03-15 12:18 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [x] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

For a single contact or name, I have written several phone numbers and for each of them there is a label.
In the window of your application, with the French language, the label is cut off (the text is cut off). The word "phone" is not complete and the following label is hidden.

### Why do you want this feature?

In the call history, and in the 'contact' tab, I would like the label of the phone number to be visible.

### Additional information

Android 10.

**Comment by Aga-C** [comment] 2024-03-15 13:06
It's a duplicate of https://github.com/FossifyOrg/Phone/issues/106.

**Closed by Aga-C** 2024-03-15 13:06 UTC
Labels: feature request, needs triage
