### ISSUE TITLE
To be able to make calls from the Contacts tab of the application

### ISSUE THREAD

**Issue by franco27** [FossifyOrg/Phone#140] opened 2024-03-20 22:11 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [X] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Android 10

Hello,

When I search in the call history, I can call the contact. However, when the contact is not in the call history and I search in the Contacts tab of the application, I cannot call the contact directly because the application does not allow it.

I find this absurd. When I long press on a contact in this tab, I do not have a menu to call this contact. And when I click on a contact, I am redirected to Google's Contacts Manager application.

This should be improved and thank you in advance.

### Why do you want this feature?

I would like to be able to make a phone call from the Contacts tab just like in the call history tab.

**Comment by Aga-C** [comment] 2024-03-20 22:19
It's a duplicate of https://github.com/FossifyOrg/Phone/issues/80.

**Closed** 2024-03-20 22:19 UTC
Labels: feature request, needs triage
