### ISSUE TITLE
Rejected calls not showing in call history

### ISSUE THREAD

**Issue by Rudde** [FossifyOrg/Phone#159] opened 2024-03-29 15:15 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Phone/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).

### Affected app version

1.1.1

### Affected Android/Custom ROM version

Android 12

### Affected device model

Samsung Galaxy S10

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Have Fossify Phone as your phone app
2. Receive call (in my case from a person in my contacts)
3. Reject call

### Expected behavior

I except to see the call I rejected in my call history so I can call back. 

### Actual behavior

There is no indication in call history of the Fossify Phone app that there has ever been a call that was rejected or otherwise

**Comment by Aga-C** [comment] 2024-03-29 15:48
It's a duplicate of https://github.com/FossifyOrg/Phone/issues/146.

**Closed by Aga-C** 2024-03-29 15:48 UTC
Labels: bug, needs triage
