### ISSUE TITLE
Make it easier to choose SIM card when calling a contact using the dial pad

### ISSUE THREAD

**Issue by tomcodemusic** [FossifyOrg/Phone#232] opened 2024-08-20 12:52 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

When I want to call a contact, I usually open the dial pad and start inputting numbers / letters, until I found the contact (NOTE: I do _not_ input the full number or name, since I only need to find the contact).

Now, I want to choose, with which SIM card I call this contact. I can long press the contact, open the three dots menu and then choose the SIM card.

Instead, I would like to have the option to immediately choose the SIM card to call from. My suggestions on how to do this would be (only one is needed):

- Add an option, which fills in the number of the contact upon tapping on it in the results list, rather than calling the number, which is currently put in (and is most likely incomplete or just the result from using the letters from the dial pad), such that I subsequently can tap on the call button of the respective SIM card
- When the option to confirm a call before dialing is active, give the choice, which SIM card to use in the popup window, which appears after tapping on the wiggling phone icon.
- Allow to temporarily switch the default SIM card before calling (e.g. by allowing to move the respective call button below the dial pad to the center and thus defining the default).

### Why do you want this feature?

Being required to use the three dots menu for choosing the SIM seems rather tedious to me and I thought of some (in my opinion) more straigthforward methods.

**Comment by Aga-C** [comment] 2024-08-20 13:31
It's a duplicate of https://github.com/FossifyOrg/Phone/issues/148.

**Closed by Aga-C** 2024-08-20 13:31 UTC
Labels: feature request, needs triage
