### ISSUE TITLE
[bug] the dialpad can't be used on landscape orientation

### ISSUE THREAD

**Issue by throwaway242685** [FossifyOrg/Phone#238] opened 2024-09-08 21:34 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Phone/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).

### Affected app version

1.2.0

### Affected Android/Custom ROM version

Android 9

### Affected device model

Samsung Galaxy A10

### How did you install the app?

GitHub releases

### Steps to reproduce the bug

1. navigate through the app on landscape orientation.
2. everything works fine until you open the dialpad, which forces the phone to go back to vertical orientation.

### Expected behavior

the dialpad should work on landscape orientation.

### Actual behavior

the dialpad forces the phone to go back to vertical orientation.

### Screenshots/Screen recordings

![screenshot_20240908-211054.png](https://github.com/user-attachments/assets/80c6697f-4827-43d7-9644-819b7cb1352b)

**Comment by Aga-C** [comment] 2024-09-09 05:26
It would be nice to have it displayed like in Google's app.

![image](https://github.com/user-attachments/assets/9f773092-ccc6-4e9b-a564-edccfe9a896c)

**Comment by naveensingh** [comment] 2024-09-09 05:43
Isn't this a duplicate of https://github.com/FossifyOrg/Phone/issues/184 (see https://github.com/FossifyOrg/Phone/issues/184#issuecomment-2123873038)? Both issues are about the app not respecting device orientation.

**Comment by Aga-C** [comment] 2024-09-09 06:03
I think it's different, because dialpad always forces portrait mode.

**Closed by Aga-C** 2024-09-09 06:03 UTC
Labels: enhancement

**Comment by throwaway242685** [comment] 2024-09-09 06:17
here are some pictures of the stock dialer app of my phone (com.samsung.android.dialer), in case that it can help of something:

| ![screenshot_20240909-030123](https://github.com/user-attachments/assets/48575fc1-95bb-4390-9adc-7725263079bc) | ![screenshot_20240909-030141](https://github.com/user-attachments/assets/9724ba7a-64da-4cd1-bc1e-9de32336f45c) |
| --- | --- |
