### ISSUE TITLE
Ability to call from contacts page in the phone app without having to install a contacts app

### ISSUE THREAD

**Issue by rmj-maker** [FossifyOrg/Phone#281] opened 2024-11-22 05:10 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [X] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Ability to call from contacts page in the phone app without having to install a contacts app. Right now I get the error - No contacts app installed.

### Why do you want this feature?

I don't use any contacts app in android. I edit in Google Contacts directly on their website.

**Comment by Aga-C** [comment] 2024-11-22 06:13
It's a duplicate of https://github.com/FossifyOrg/Phone/issues/80.

**Closed by Aga-C** 2024-11-22 06:13 UTC
Labels: feature request, needs triage
