### ISSUE TITLE
Dialer does not respect Contact Storage Accounts

### ISSUE THREAD

**Issue by pudup** [FossifyOrg/Phone#176] opened 2024-04-24 08:05 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Phone/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).

### Affected app version

1.1.1

### Affected Android/Custom ROM version

Android 13

### Affected device model

Moto G

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Have multiple contact accounts, i.e Local, WhatsApp, CalDav etc.
2. Set dialer to only display one. Say CalDav.
3. Click a contact that is present in multiple accounts.

### Expected behavior

It should open the contact in the selected account

### Actual behavior

It opens a seemingly random account
In my case I have it set to only display decsync account but it opens the contact display for the whatsapp account

This is a problem because the whatsapp account only has one number saved to it while the decsync contact info has multiple numbers and now I don't have the option to choose the desired number to dial

**Comment by Aga-C** [comment] 2024-04-24 08:32
It's a duplicate of https://github.com/FossifyOrg/Phone/issues/73.

**Closed by Aga-C** 2024-04-24 08:32 UTC
Labels: bug, needs triage
