### ISSUE TITLE
Notifications don't show missed calls

### ISSUE THREAD

**Issue by khoin343** [FossifyOrg/Phone#123] opened 2024-02-24 01:16 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Phone/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.0

### Affected Android/Custom ROM version

Android 14/One UI 6.0

### Affected device model

Samsung Galaxy A14 5G

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Miss a call from someone

### Expected behavior

The app to show a notification saying that you missed a call.

### Actual behavior

The Samsung app giving the notification instead.

**Comment by Aga-C** [comment] 2024-02-24 06:42
It's a duplicate of https://github.com/FossifyOrg/Phone/issues/83.

**Closed by Aga-C** 2024-02-24 06:42 UTC
Labels: bug, needs triage
