### ISSUE TITLE
Checkbox for recording calls automatically.

### ISSUE THREAD

**Issue by GamePlayer-8** [FossifyOrg/Phone#219] opened 2024-08-04 12:12 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Good morning,

I'm missing an option to automatically record calls onto my phone without having to press the record button every time the call starts.

### Why do you want this feature?

Whenever I talk with someone, I want to save the conversation on later and easier to know what they have said to me.

**Comment by Aga-C** [comment] 2024-08-04 12:40
It's a duplicate of https://github.com/FossifyOrg/Phone/issues/17.

**Closed** 2024-08-04 12:40 UTC
Labels: feature request, needs triage
