### ISSUE TITLE
We must able to reject incoming calls by sending sms with fast response.

### ISSUE THREAD

**Issue by yusufsunetci** [FossifyOrg/Phone#138] opened 2024-03-20 13:11 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [X] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

We must able to reject incoming calls by sending sms with fast response.
For example:
I'm in a meeting.
I'm driving a car.
I can't answer it now. I'll call you later.

### Why do you want this feature?

It is more convenient to use it like this.

**Comment by Aga-C** [comment] 2024-03-20 13:32
It's a duplicate of https://github.com/FossifyOrg/Phone/issues/4.

**Closed by Aga-C** 2024-03-20 13:32 UTC
Labels: feature request, needs triage

**Comment by yusufsunetci** [comment] 2024-03-20 13:46
As I understand, this issue isn't a duplicate of it.

It wants sms to go to all missed calls automatically. But I want to reject incoming calls by sms. Some of the calls.

If it's the same... No problem. Just let the problem be solved. :)
