### ISSUE TITLE
Add space after country code in call history

### ISSUE THREAD

**Issue by Rexadev** [FossifyOrg/Phone#62] opened 2024-01-25 07:13 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

+1234567 it is hard to tell if the country code is +1 or +12

### Why do you want this feature?

It would make it look clean and easy to read

**Comment by inson1** [comment] 2024-02-05 23:50
I think this is duplicate of https://github.com/FossifyOrg/Contacts/issues/15
its still saved, doesnt matter where

**Comment by Aga-C** [comment] 2024-02-06 06:34
@inson1 No. It's similar, but it's a completely different place and has to be done separately.

**Closed** 2024-05-02 05:00 UTC
Labels: enhancement

**Comment by naveensingh** [comment] 2024-05-02 05:07
It'll be available in the next update.
