### ISSUE TITLE
[Feature Request] Scheduled Backup for History Call Log 

### ISSUE THREAD

**Issue by mahdiaqallal** [FossifyOrg/Phone#228] opened 2024-08-10 14:11 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

This is a GREAT App and thanks @Aga-C  for the lighting answer to my previous feature request in #223 

Since by design, the app has no Internet access, which is a great security and privacy design goal (so no syncing), can we pivot to a Scheduled Backup for History Call Log Feature request ?

**Feature description**

To enhance this great app I would like to propose a feature :

- Scheduled Backup the History Call Log
- Prompt in settings for i.e. hourly, daily, weekly, monthly scheduled backup
- Prompt in settings for the naming template of backup File i.e. <FossiFy Phone App> <MyDeviceCallLog><DateTime> or other custom fields to include in the backup file's name (device model, Device name or model type etc...)

- Define the Backup Folder in settings so as to grant permission to app (device's storage or SD-Card, and so on)
- Address logic about whether the next scheduled backup should overwrite the previous one or be added along in folder
- Optional password/PIN definition in settings to secure the backup file

I may  edit this request with examples of other Apps providing usefull designs Scheduled Backups and if they are FOSS, the better !

### Why do you want this feature?

It would add seamless:

- Security and recovery by scheduled backup into backup folder
- Privacy when coupled with syncing of the backup Folder : WebDav with Davx5 for example

This would enable syncing in two-steps while aligning with the App's "no Internet by design" policy for the uses cases:
 - Backup by having an off device, online backup of the history call log (lost, stolen device)
 - Device Transfer: easier switch to a new device (update, change, recovery) by uploading the latest or chosen scheduled / on demand file stored or retrieved from online storage

### Additional information

None

**Comment by Aga-C** [comment] 2024-08-10 14:17
It's a duplicate of https://github.com/FossifyOrg/Phone/issues/224. You can add your remarks there.

**Closed by Aga-C** 2024-08-10 14:17 UTC
Labels: feature request, needs triage
