### ISSUE TITLE
Customization Option for dialer

### ISSUE THREAD

**Issue by Lorograch1** [FossifyOrg/Phone#269] opened 2024-11-05 18:22 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

When a call comes, the user swipes left or right to decline or answer a call. I would like an option to make it up or down for this functionality, if possible. 

### Why do you want this feature?

Easier and accustomed to HyperOS version.

**Comment by Aga-C** [comment] 2024-11-05 18:33
It's a duplicate of https://github.com/FossifyOrg/Phone/issues/175.

**Closed by Aga-C** 2024-11-05 18:33 UTC
Labels: feature request, needs triage
