### ISSUE TITLE
"Ghost" call notification after call had ended

### ISSUE THREAD

**Issue by sosauce** [FossifyOrg/Phone#276] opened 2024-11-13 16:30 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Phone/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).

### Affected app version

1.3.0

### Affected Android/Custom ROM version

MIUI 14 - Android 13

### Affected device model

Redmi Note 10 5G

### How did you install the app?

GitHub releases

### Steps to reproduce the bug

1. Call or get called
2. You or caller hang up
3. Check your notifications and something the call notification will stay

⚠️ Please note that this bug seems to be random, has I haven't found a consistent way of doing it !

### Expected behavior

No more call notification after hanging up

### Actual behavior

Call notification still here after hanging up (Plus the counter of time spent on call still goes up)

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/6f40eca1-cb90-4435-90dd-66a4529d34ad

### Additional information

- Seems to be random
- Timer of spent time on call still goes up

**Comment by Aga-C** [comment] 2024-11-13 16:54
It's a duplicate of https://github.com/FossifyOrg/Phone/issues/58.

**Closed by Aga-C** 2024-11-13 16:54 UTC
Labels: bug, needs triage

**Comment by sosauce** [comment] 2024-11-13 17:49
Thanks, didn't see this
