### ISSUE TITLE
Send message from dialpad

### ISSUE THREAD

**Issue by jcperil** [FossifyOrg/Phone#144] opened 2024-03-21 20:41 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Next to the + button on top right, can you add a button for sending a message from the dialpad?
<p align=center><img src="https://github.com/FossifyOrg/Phone/assets/89805719/1d7ad147-3a34-4d1a-a844-a96e08abd97a" height="300px"/></p>

It will redirect the user to the SMS app with the number on the dialpad as the default recipient.

### Why do you want this feature?

It saves you a few clicks from copying the number from dialpad, go to SMS app and resume your thought of what you want to write. Also provides a sense of interoperability between dialer and SMS app.

**Comment by Aga-C** [comment] 2024-03-21 20:56
It's a duplicate of https://github.com/FossifyOrg/Phone/issues/12.

**Closed by Aga-C** 2024-03-21 20:56 UTC
Labels: feature request, needs triage
