### ISSUE TITLE
Block calls using ratings database

### ISSUE THREAD

**Issue by vertigo220** [FossifyOrg/Phone#101] opened 2024-02-04 03:31 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Use a database to block numbers with low ratings. This could be an open-source and/or community-driven, where users rate a number as spam or not. Not sure if there's already such a non-proprietary database out there. Yet Another Call Blocker uses this feature, but unfortunately that app has been abandoned, and I can't tell what database it uses. I tried searching for an open one that could be used but wasn't able to immediately find anything, though I'm happy to dig more if this is a feature that would be implemented.

### Why do you want this feature?

To assist in blocking spam calls. I don't like blocking any unknown/non-contact call, as I get some legitimate ones, and YACB's database feature works fairly well in notifying if a call is a spam risk, something I find useful. Unfortunately, that database is out-of-date and the app itself is abandoned, so having a similar feature built in to this app would be great, especially since certain features require this app to be set as the default phone app, which then prevents other apps from performing such functions, making it more important that this app can take on those responsibilities.

**Comment by Aga-C** [comment] 2024-02-04 07:06
It's a duplicate of https://github.com/FossifyOrg/Phone/issues/32.

**Closed by Aga-C** 2024-02-04 07:06 UTC
Labels: feature request, needs triage
