### ISSUE TITLE
Unable to return to call if the app gets closed

### ISSUE THREAD

**Issue by xfarrow** [FossifyOrg/Phone#122] opened 2024-02-21 10:39 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Phone/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.0

### Affected Android/Custom ROM version

Android 13

### Affected device model

Xiaomi Redmi Note 11S

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

If I close the app while there is a call going on, I can keep hearing the other person, but I am unable to return to the "ongoing call" screen, hence unable to hang up, mute, or do anything else. The notification with the red hang up icon will still be there, but clicking on it shall have no effect. The only way to hang up in this scenario is to reboot the smartphone. I don't know whether it is an Android limitation though.

Steps:

1. Initiate (or receive a call)
2. Close the application (meaning closing it from the "open apps")
3. You'll still be able to hear the other person, unable to hang up because if you open the application, it will not show there is an ongoing call.

### Expected behavior

Show that there is an ongoing call even if the app gets terminated

### Actual behavior

The app does not show there is a call, being unable to hang up

**Comment by Aga-C** [comment] 2024-02-21 11:05
It's a duplicate of https://github.com/FossifyOrg/Phone/issues/105.

**Closed** 2024-02-21 11:05 UTC
Labels: bug, needs triage
