### ISSUE TITLE
Incoming call not displaying

### ISSUE THREAD

**Issue by systemd11** [FossifyOrg/Phone#201] opened 2024-05-22 17:00 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Phone/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).

### Affected app version

1.2.0 

### Affected Android/Custom ROM version

LineageOS 20 (Android 13)

### Affected device model

Redmi Note 10 Pro

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

When I get an incoming call on the Phone app, there's no splash screen, no notification. Sounds work. My only option is to manually open the phone app which enables me to answer the call. 

### Expected behavior

Some kind of splash screen to answer the call.

### Actual behavior

No splash screen showing up.

**Comment by naveensingh** [comment] 2024-05-22 17:06
Please try the solutions here:

 - https://github.com/FossifyOrg/Phone/issues/108#issuecomment-1936318070
 - https://www.reddit.com/r/Fossify/comments/1acq4ic/fossify_phone_when_i_get_a_call_l_need_to_unlock/

**Comment by naveensingh** [comment] 2024-05-22 17:07
@systemd11 Please check if the app has 'Display over other apps' permission.

**Comment by systemd11** [comment] 2024-05-22 17:18
@naveensingh Yes it does

**Comment by Aga-C** [comment] 2024-05-22 17:20
It's a duplicate of https://github.com/FossifyOrg/Phone/issues/142.

**Closed by Aga-C** 2024-05-22 17:20 UTC
Labels: bug, needs triage

**Comment by naveensingh** [comment] 2024-05-22 17:26
I guess it's an app issue then.

**Comment by th3kumar** [comment] 2024-07-26 07:05
hey @naveensingh , @Aga-C  is it fixed ? this issue is frequently bothering

**Comment by naveensingh** [comment] 2024-07-26 07:07
I have had trouble reproducing it. I will try again soon. Any updates will be posted on the issue linked by Aga-C above.

**Comment by th3kumar** [comment] 2024-07-26 08:35
@naveensingh for my device "vivo 1915" Call Notification is added to Notification Center after 4,5 seconds, even the priority is low, hence I had to swipe and search for the calling notification.

thanks for replying though.
