### ISSUE TITLE
Add an option for ID display or call block based on public databases

### ISSUE THREAD

**Issue by alberteinst4** [FossifyOrg/Phone#282] opened 2024-11-22 09:12 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Add an option for ID display or call block based on public databases (eg. truecaller), similar to what DreadedLama has done here:
https://github.com/DreadedLama/Simple-Dialer  

### Why do you want this feature?

I get a lots of spam calls using unknown numbers, it would help to know those are spams before I pickup those calls. A lot of times I miss genuine calls because of habit of ignoring unknown calls. Truecaller database is the biggest caller id database but Truecaller is a proprietary closed source app with lots of trackers and ads. Adding feature to configure other public databases would be appreciated. 

### Additional information
the feature would first check incoming number on local contacts, if not found then check if public databases are configured, if yes search the number on public database and display information.

_No response_

**Comment by Aga-C** [comment] 2024-11-22 09:15
It's a duplicate of https://github.com/FossifyOrg/Phone/issues/32.

**Closed by Aga-C** 2024-11-22 09:15 UTC
Labels: feature request, needs triage
