### ISSUE TITLE
Grouping more calls as one entry (separated by phone number) doesn't work as expected

### ISSUE THREAD

**Issue by serrq** [FossifyOrg/Phone#156] opened 2024-03-28 08:51 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Phone/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).

### Affected app version

1.1.1

### Affected Android/Custom ROM version

Android 14

### Affected device model

OnePlus CPH2399

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

Do nothing. It is so.

### Expected behavior

Grouping all (events) calls as one only. With "see more details" option.

### Actual behavior

There, four entries for a same contact.

**Comment by Aga-C** [comment] 2024-03-28 08:57
It's a duplicate of https://github.com/FossifyOrg/Phone/issues/45.

**Closed by Aga-C** 2024-03-28 08:57 UTC
Labels: duplicate

**Comment by naveensingh** [comment] 2024-05-01 22:09
Fixed in https://github.com/FossifyOrg/Phone/commit/0550873225fa6e853e26f085d6ff6e68a587ae92
