### ISSUE TITLE
No 'In call' view shown allowing for hang up (and other actions) if user navigates away.

### ISSUE THREAD

**Issue by verbunk** [FossifyOrg/Phone#182] opened 2024-05-05 19:45 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Phone/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).

### Affected app version

1.1.1

### Affected Android/Custom ROM version

Android 14

### Affected device model

Surface Duo

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Make call
2. During call, navigate away to another app

### Expected behavior

A separate view of the Phone app is spawned which has the actions and is maintained for the duration of the call. 

### Actual behavior

There is no 'In Call' app / mode / view of the Fossify Phone app maintained through the call so I cannot switch back to end call once navigated away. There is a notification card of an in-progress call which contains a 'hang up' icon. Pressing this does flash the button (signifying it was pressed) but the button does not hang up the call.

There is a notification in Android top status bar (next to battery meter) that the Mic is in use during this time.

### Additional information

None known

**Comment by Aga-C** [comment] 2024-05-05 20:10
It's a duplicate of https://github.com/FossifyOrg/Phone/issues/105.

**Closed by Aga-C** 2024-05-05 20:10 UTC
Labels: bug, needs triage

**Comment by verbunk** [comment] 2024-05-05 20:19
Hey Aga-C ; thanks for the followup. I didn't associate #105 as close enough (but it's true of the notification part). Is it expected that the 'In-Call' view should go away?

**Comment by Aga-C** [comment] 2024-05-05 20:43
It's not an expected behavior, that's why #105 is still open.
