### ISSUE TITLE
Unique modular backup (and restore) 

### ISSUE THREAD

**Issue by serrq** [FossifyOrg/Phone#154] opened 2024-03-28 06:50 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

I need that these three apps have the same unique and modular backup:
• Phone
• Contacts book
• Messages (SMS)

### Why do you want this feature?

Easily backup and restore everything over three apps (if installed) carrying on just one backup file (zip or json, etc.).

**Comment by Aga-C** [comment] 2024-03-28 07:15
It's a duplicate of https://github.com/orgs/FossifyOrg/discussions/106.

**Closed by Aga-C** 2024-03-28 07:15 UTC
Labels: feature request, needs triage
