### ISSUE TITLE
Option to show timestamp in Call History tab

### ISSUE THREAD

**Issue by BloodRaven0** [FossifyOrg/Phone#168] opened 2024-04-07 10:45 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

There should be an option to toggle showing the timestamps for calls in the call history tab, after the date.
For example, instead of just showing 06.04 below a call, it should show "06.04, 12:20" (or "06 April, 12:20", depending on user date settings)
If call grouping it enabled, it should show the timestamp of the earliest call.

### Why do you want this feature?

This information is very useful, and it shouldn't be hidden in the three dot menu. It's such a basic feature, that I'd argue the option should also be enabled by default.

### Additional information

Reposting https://github.com/FossifyOrg/Phone/issues/167 , because my github app didn't support templates.

**Comment by Aga-C** [comment] 2024-04-07 10:59
It's a duplicate of https://github.com/FossifyOrg/Phone/issues/96.

**Closed by Aga-C** 2024-04-07 10:59 UTC
Labels: feature request, needs triage
